"""initial

Revision ID: 7d2f97762d3b
Revises: 
Create Date: 2026-06-18 15:25:09.875517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2f97762d3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venta_csv', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('producto', sa.String(length=180), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_venta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=80), nullable=False),
    sa.Column('sucursal', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('vendedor', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_venta_csv')
    )
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventas_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_ciudad'), ['ciudad'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_metodo_pago'), ['metodo_pago'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_producto'), ['producto'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_sucursal'), ['sucursal'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_total_venta'), ['total_venta'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_vendedor'), ['vendedor'], unique=False)

    op.create_table('bitacora_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('evento', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitacora_acceso')
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventas_vendedor'))
        batch_op.drop_index(batch_op.f('ix_ventas_total_venta'))
        batch_op.drop_index(batch_op.f('ix_ventas_sucursal'))
        batch_op.drop_index(batch_op.f('ix_ventas_producto'))
        batch_op.drop_index(batch_op.f('ix_ventas_metodo_pago'))
        batch_op.drop_index(batch_op.f('ix_ventas_fecha'))
        batch_op.drop_index(batch_op.f('ix_ventas_ciudad'))
        batch_op.drop_index(batch_op.f('ix_ventas_categoria'))

    op.drop_table('ventas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
